application: filewallah
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# - url: /static 
#   static_dir: static

- url: /static/css 
  mime_type: text/css
  static_dir: static/css

- url: /static/js
  mime_type: text/javascript
  static_dir: static/js
  
- url: /static/img/(.*\.png) 
  static_dir: static/img
 

- url: .*
  script: main.app 


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
