application: filewallah
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static 
  static_dir: static
- url: /required
  script: main.app
  login: required  

- url: /
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
